### PR TITLE
Return a promise for configuring

### PR DESCRIPTION
**Pull request by tkuenzle**
The native code returns a promise, which has been ignored by the JS
code. Return it and update the example usage.

Resolves: https://github.com/timfpark/react-native-location/issues/57

### CODE REVIEW

**Comment by matt-oakes** [comment]
Thank you for this! This looks good, but you can also change the "standard location provider" to resolve the promise to avoid it getting stuck if using that provider:

https://github.com/timfpark/react-native-location/blob/8ff3823fe131e03415cec1e88ab7dd5aab904ff9/android/src/main/java/com/github/reactnativecommunity/location/RNStandardLocationProvider.java#L30-L36

**Comment by tkuenzle** [comment]
Sorry for that! I just added one line to resolve the promise. Inside the `setupListening` method there are a few cases, where configuring actually fails and it would be nice to reject the promise in those cases. It's also used from `startUpdatingLocation` however, where we do not have a promise.

Either we pass the promise to `setupListening` and reject the promise if we have one. Or we just leave it for now... :)

**Comment by tkuenzle** [comment]
@matt-oakes I did the changes you requested, but as I force pushed, I cannot answer them...

**Comment by matt-oakes** [comment]
This looks great! Thanks for the changes :+1:

**Pull request merged**
